"""Initial migration

Revision ID: d5f5021963d5
Revises: 
Create Date: 2025-02-11 17:03:48.609740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5f5021963d5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('spell_type', sa.String(), nullable=True))
    op.create_index('idx_card_name', 'cards', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_card_name', table_name='cards')
    op.drop_column('cards', 'spell_type')
    # ### end Alembic commands ###
